name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt
    - name: Analysing the code with pylint & black
      run: |
        pylint --disable=all --enable=unused-import $(git ls-files '*.py')
        black --diff --check $(git ls-files '*.py')
        isort $(git ls-files '*.py')
    - name: Run pytest
      run: |
         pytest $(git ls-files 'test_*.py')



